"""empty message

Revision ID: 20d2b40a57d9
Revises: af956d77be6a
Create Date: 2017-05-29 10:41:49.329040

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20d2b40a57d9'
down_revision = 'af956d77be6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('meal', 'location_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'location_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('location', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
