"""Alters meal.scheduled_for WITH TIMEZONE, adds NOT NULL constraint to \
users.first_name and users.last_name

Revision ID: 3e4b230c5582
Revises: ddd00fbe2758
Create Date: 2017-07-01 10:47:47.789316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4b230c5582'
down_revision = 'ddd00fbe2758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meal', 'scheduled_for', existing_type=sa.DateTime(),
                    type_=sa.DateTime(timezone=True), nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('meal', 'scheduled_for',
                    existing_type=sa.DateTime(timezone=True),
                    type_=sa.DateTime(timezone=True), nullable=False)
    # ### end Alembic commands ###
