"""Removes the host_id from the Location model

Revision ID: 94f88d0bf9bb
Revises: ab25240c9bf9
Create Date: 2017-05-20 16:37:48.962292

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '94f88d0bf9bb'
down_revision = 'ab25240c9bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('location_host_id_fkey', 'location', type_='foreignkey')
    op.drop_column('location', 'host_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('host_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('location_host_id_fkey', 'location', 'users', ['host_id'], ['id'])
    # ### end Alembic commands ###
