"""Adds the users <-> location tables FK

Revision ID: ab25240c9bf9
Revises: f9a432f6a0b2
Create Date: 2017-05-18 21:21:59.969585

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab25240c9bf9'
down_revision = 'f9a432f6a0b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('host_id', sa.Integer()))
    op.create_foreign_key(None, 'location', 'users', ['host_id'], ['id'])
    op.add_column('users', sa.Column('location_id', postgresql.UUID(as_uuid=True)))
    op.create_foreign_key(None, 'users', 'location', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'location_id')
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'host_id')
    # ### end Alembic commands ###
