"""Changes the location <-> meal m2m table to user <-> meal m2m table.

Revision ID: af956d77be6a
Revises: 9628d0303d10
Create Date: 2017-05-24 00:18:02.563617

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af956d77be6a'
down_revision = '9628d0303d10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'user_meal',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('meal_guid', postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(['meal_guid'], ['meal.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('user_id', 'meal_guid')
    )
    op.drop_table('location_meal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'location_meal',
        sa.Column('location_guid', postgresql.UUID(),
                  autoincrement=False, nullable=False),
        sa.Column('meal_guid', postgresql.UUID(),
                  autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['location_guid'], ['location.id'],
                                name='location_meal_location_guid_fkey'),
        sa.ForeignKeyConstraint(['meal_guid'], ['meal.id'],
                                name='location_meal_meal_guid_fkey'),
        sa.PrimaryKeyConstraint('location_guid', 'meal_guid',
                                name='location_meal_pkey')
    )
    op.drop_table('user_meal')
    # ### end Alembic commands ###
