"""Creates the tag and meal_tags tables.

Revision ID: b8382b9376b1
Revises: 7c5a1a92c81f
Create Date: 2017-09-16 10:27:07.969043

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8382b9376b1'
down_revision = '7c5a1a92c81f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_alias'), 'tag', ['alias'], unique=False)
    op.create_table('meal_tag',
    sa.Column('meal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('meal_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_tag')
    op.drop_index(op.f('ix_tag_alias'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
