"""Adds users.stripe_customer_id column and the transaction table

Revision ID: e63d9d5e76a9
Revises: 9f2495bd66de
Create Date: 2017-07-24 22:44:33.650136

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e63d9d5e76a9'
down_revision = '9f2495bd66de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meal_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('payee_id', sa.Integer(), nullable=False),
    sa.Column('transaction_went_through', sa.Boolean(), nullable=False),
    sa.Column('transaction_paid_out', sa.Boolean(), nullable=False),
    sa.Column('canceled', sa.Boolean(), nullable=False),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('stripe_idempotency_key', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('stripe_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_table('transaction')
    # ### end Alembic commands ###
