"""Creates initial user, role, and location tables

Revision ID: f9a432f6a0b2
Revises:
Create Date: 2017-05-18 18:59:02.103067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f9a432f6a0b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('raw_yelp_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('yelp_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_class', sa.Integer(), nullable=True),
    sa.Column('exact_price', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_exact_price'), 'location', ['exact_price'], unique=False)
    op.create_index(op.f('ix_location_price_class'), 'location', ['price_class'], unique=False)
    op.create_index(op.f('ix_location_source'), 'location', ['source'], unique=False)
    op.create_index(op.f('ix_location_yelp_id'), 'location', ['yelp_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('users')
    op.drop_index(op.f('ix_location_yelp_id'), table_name='location')
    op.drop_index(op.f('ix_location_source'), table_name='location')
    op.drop_index(op.f('ix_location_price_class'), table_name='location')
    op.drop_index(op.f('ix_location_exact_price'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
