
const CeraonActionType = {
  NotAuthorized: 'NotAuthorized',
  PageNotFound404: 'PageNotFound404',
  LoadState: 'LoadState',
  Login: 'Login',
  MealSearch: 'MealSearch',
  GoHome: 'GoHome',
  ViewMeal: 'ViewMeal',
  StartLoading: 'StartLoading',
  MealLoaded: 'MealLoaded',
  SearchResultsLoaded: 'SearchResultsLoaded',
  MyMealsLoaded: 'MyMealsLoaded',
  MealUpdated: 'MealUpdated',
  UpdateMeal: 'UpdateMeal',
  CancelMeal: 'CancelMeal',
  MealCancelled: 'MealCancelled',
  Landing: 'Landing',
  GoToSettings: 'GoToSettings',
  GoToCreateMeal: 'GoToCreateMeal',
  GoToEditMeal: 'GoToEditMeal',
  CreateMeal: 'CreateMeal',
  UpdateUser: 'UpdateUser',
  UserUpdated: 'UserUpdated',
  MealCreated: 'MealCreated',
  ToggleJoinMeal: 'ToggleJoinMeal',
  UpdatePaymentInfo: 'UpdatePaymentInfo',
  CreateReview: 'CreateReview',
  ReviewCreated: 'ReviewCreated',
  HostedMealsLoaded: 'HostedMealsLoaded',
  JoinedMealsLoaded: 'JoinedMealsLoaded',
  MealTagsLoaded: 'MealTagsLoaded',
  FetchTags: 'FetchTags',
};

export default CeraonActionType;
